version: "3"

services:
  imagetranslate:
    image: llearnell/indictranslate
    container_name: indictranslate
    restart: "unless-stopped"
    ports:
      - "7860:7860"  # Using default port from the image
    
    deploy:
      resources:
        limits:
          memory: 12288M
          cpus: 16
